import fs from 'fs';
import path from 'path';

const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
const outputPath = './src/wasm-from-cdn.ts';

const version = packageJson.version;
const repoUrl = packageJson.repository.url.replace('git+', '').replace('.git', '');
const outputContent = `
// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  'single-thread/wllama.wasm': '${repoUrl}/releases/download/v${version}/wllama-single-thread.wasm',
  'multi-thread/wllama.wasm': '${repoUrl}/releases/download/v${version}/wllama-multi-thread.wasm',
};

export default WasmFromCDN;
`.trim();

fs.writeFileSync(outputPath, outputContent);
