// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  'single-thread/wllama.wasm': 'https://github.com/alpaim/wllama/releases/download/v2.3.7/wllama-single-thread.wasm',
  'multi-thread/wllama.wasm': 'https://github.com/alpaim/wllama/releases/download/v2.3.7/wllama-multi-thread.wasm',
};

export default WasmFromCDN;